# Copyright 2006 The Android Open Source Project

ifdef WIFI_DRIVER_NO_RFKILL
LOCAL_CFLAGS += -DWIFI_DRIVER_NO_RFKILL
endif
ifdef WIFI_DRIVER_ONLY_ONE_MODULE
LOCAL_CFLAGS += -DWIFI_DRIVER_ONLY_ONE_MODULE
endif
ifdef WIFI_DRIVER_MODULE_1_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_1_PATH=\"$(WIFI_DRIVER_MODULE_1_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_1_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_1_ARG=\"$(WIFI_DRIVER_MODULE_1_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_1_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_1_NAME=\"$(WIFI_DRIVER_MODULE_1_NAME)\"
endif
ifdef WIFI_DRIVER_MODULE_2_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_2_PATH=\"$(WIFI_DRIVER_MODULE_2_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_2_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_2_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_2_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_2_NAME=\"$(WIFI_DRIVER_MODULE_2_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_NETIFAC_NAME
LOCAL_CFLAGS += -DWIFI_NETIFAC_NAME=\"$(WIFI_NETIFAC_NAME)\"
endif
ifdef WIFI_RFKILL_UTILS
LOCAL_CFLAGS += -DWIFI_RFKILL_UTILS
endif

ifeq ($(TARGET_PRODUCT),generic)
LOCAL_SRC_FILES += wifi/wifi.c
else
ifeq ($(WIFI_CHIP_TYPE),8787)
LOCAL_SRC_FILES += wifi/mrvl8787_wifi.c
$(info libhardware_legacy:wifi:building marvell wifi SD8787)
else
LOCAL_SRC_FILES += wifi/marvell_wifi.c
$(info libhardware_legacy:wifi:building marvell wifi SD8688)
endif
endif

LOCAL_SHARED_LIBRARIES += libnetutils libMarvellWireless
